### ISSUE TITLE
macOS: declare: -A: invalid option

### ISSUE THREAD

**Issue by joshjohanning** [andyfeller/gh-repo-export#11]
The latest update to support a repos.txt file broke on my machine :( 

```bash
$ gh repo-export joshjohanning-org repos.txt
Reading repositories from file: repos.txt
/Users/joshjohanning/.local/share/gh/extensions/gh-repo-export/gh-repo-export: line 142: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

Looks like this might not work out of the box for macOS without updating `bash`? 

My bash version:

```bash
$ bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)
Copyright (C) 2007 Free Software Foundation, Inc.
```

https://stackoverflow.com/questions/6047648/associative-arrays-error-declare-a-invalid-option
https://www.ianoutterside.com/bash-invalid-option/

I can probably update my bash, but I'm assuming others may run into this as well. Unsure if there is a different way to solve this without using the `declare -A` command?

**Comment by andyfeller** [comment]
@joshjohanning : Thanks for letting me know!  Historically, I kept to using the older Apple Bash 3.2.x but needed to upgrade for one concern or another.

Let me take this as a follow up on how to support these changes for those on MacOS; thank you for the report and apologies for breaking things 🙇 

In the mean time, you should be able to pin this to the prior version via:

```shell
gh extension remove andyfeller/gh-repo-export
gh extension install andyfeller/gh-repo-export --pin 404a2268ca36a0455457d3a3da1be0537a68e465
```

or

```shell
gh extension install andyfeller/gh-repo-export --pin v1.1.0
```

**Comment by joshjohanning** [comment]
Thank you! Your new update resolved for me 😀 🎉
